### ISSUE TITLE
bug:linkSrc error

### ISSUE THREAD

**Issue by LyZane** [TakuroFukamizu/gitbook-plugin-include-csv#3]
folder structure:
```html
gitbook-root/
      hello/
            static/
                  api.csv
            README.md
```

README.md:
```html
{% includeCsv src="static/api.csv" %}{% endincludeCsv %}
```

output linkSrc:
> http://localhost:4000/hello/hello/static/api.csv

linkSrc should be:
> http://localhost:4000/hello/static/api.csv

Please fix this problem, thank you.

**Comment by TakuroFukamizu** [comment]
@LyZane Thank you for your report.
I've fixed this issue just now.

https://github.com/TakuroFukamizu/gitbook-plugin-include-csv/pull/4

It's tested on my local env. Can you double check it?
If this fix work in your env, I will release this fix to npm : )

**Comment by LyZane** [comment]
success!

Please release this fix to npm!

**Comment by TakuroFukamizu** [comment]
@LyZane Thank you for your cooperation! 
I've released a new version to the npm.

**Comment by LyZane** [comment]
I have received,Thank you for your pay.
